### ISSUE TITLE
Possible goroutine leak in rpc server

### ISSUE THREAD

**Issue by phifty** [micro/go-micro#111]
We're using the NATS transport implementation and a client without a connection pool. After a while, the server process consumes a huge amount of memory. An inspection shows, that a lot of goroutines are hanging on this line:

https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L60

My guess is, that the NATS implementation doesn't implement any close-semantic, so the server doesn't know that the client closed the socket. I'll write a test and issue a PR soon.

Maybe this issue belongs in the go-plugins repository, but maybe the rpc server could improve the socket handling too.

**Comment by asim** [comment]
This issue should be filed against go-plugins. Its not an issue related to the rpc server but the implementation of the NATS transport. Using tcp/http on socket close the blocking socket.Recv will fall through and return. With the NATS transport this does not happen because there's no signalling from the client to the server.
