### ISSUE TITLE
Handlers are not working

### ISSUE THREAD

**Issue by dinilv** [micro/go-micro#123]
HI,
I have uploaded my code below link. https://github.com/dinilv/adserver
I am trying to run micro api and then adserver/server/api/v1/MOCampaign.go . It all works fine and api discovers the listening api handler but API handler is unable to discover service API thats file adserver/server/service/v1/MOCampaign.go & adserver/services/v1/MOCampaign.go

am always getting this error, {"id":"go.micro.client","code":500,"detail":"request error","status":"Internal Server Error"}

**Comment by asim** [comment]
What request are you making? This implies that it expects a request of `/v1/mocampaign/add` or something of that nature.

**Comment by dinilv** [comment]
Hi Asim,
Thanks for the response. Since am newbie to this MSOA and go, bit struggling.
My intention is to call API through http request and it is working.
Flow is 
1. Hit API : /v1/mocampaign/add
2. The request is actknowledged by running micro api
3. server calls the correct http server, file corresponding to same is server/api/v1/MOCampaign.go & Handler file is registry/v1/MOCampaign.go
   --Upto this flow its fine and getting output on console as expected
4. From the above file am trying to find the service "go.micro.service.v1.mocampaign" and the file is  in service/v1/MOCampaign.go & handler as /service/v1/MOCampaign.go
5. This one" http://localhost:8080/v1/mocampaign/add?name=checking"
   is giving error : {"id":"go.micro.client","code":500,"detail":"request error","status":"Internal Server Error"}

Can u help out me here on registering the handler ?

**Comment by asim** [comment]
Your code is hitting an internal error which is only logged if there's some sort of panic during the request call. The code being executed is here https://github.com/micro/go-micro/blob/master/client/rpc_client.go#L101

The message is likely being swallowed so its difficult to know the exact problem. However your code appears to have a number of issues. You initialise a new service but then use the default server to register handlers. This is incorrect. You should be registering handlers with the service you just created. Your handlers also use the default client when they should be using the client within your service.

It's difficult to know whats causing the issue otherwise without logging the panic which you should probably do by modifying the rpc_client.go at line 101.

**Comment by dinilv** [comment]
Hi,
I just printed the error on the same line got this one.

"2016/09/25 19:18:28 Received MO Campaign Add Req
interface conversion: *v1.AddMOCampaignReq is not proto.Message: missing method ProtoMessage "

I didnt use the proto utility to create the stubs because i want to understand the complete flow first. Is it creating the problem ?

if am not wrong this code is not handling the registered handler with service.

//Campaign creation service
    service := micro.NewService(
        micro.Name("go.micro.api.v1.mocampaign"),
        micro.Version("1.0"),
        micro.RegisterTTL(time.Second_30),
        micro.RegisterInterval(time.Second_10),
    )
    //register handler for the service
    server.Handle(
        server.NewHandler(
            new(v1.Mocampaign),
        ),
    )

if possible could u tell me an example on the micro/micro github url ? i was trying with the examples given on the same.

**Comment by asim** [comment]
Example of registering handler https://github.com/micro/go-micro/blob/master/examples/service/main.go#L80

If you are using the default codec which is protobuf then your Request and Response types must conform to proto.Message interface. If you look at the examples of how to write services you'll clearly see the part that indicates proto definitions, compiling and using them. If you do not want to use proto and do not want to modify the client then the simplest way is to use NewJsonRequest rather than NewRequest.

**Comment by dinilv** [comment]
Thanks Asim for resolving the same . 👍 

If possible could u bit clarify these below . When am trying to create one handler for service the interface doesnt match.

:On service creation

```
  type Say struct{}
```

// Register Handlers
    hello.RegisterSayHandler(service.Server(), new(Say))

On handler:

func RegisterSayHandler(s server.Server, hdlr SayHandler) {
    s.Handle(s.NewHandler(&Say{hdlr}))
}

type Say struct {
    SayHandler
}

When am trying to declare the handler and register the same, it says the mismatch all the time.
I can see the codes are generated. so not able figure out how it matches.

**Comment by asim** [comment]
I'm not sure what you mean but your handler should match the signature defined by the proto api you create. The example is fairly clear. This is not magic but merely Go code.

This is not an issue but more a discussion on usage. Please join the micro slack if you want to discuss further. I am closing the issue itself.

**Comment by dinilv** [comment]
Thanks ASIM for the feedbacks.  Its resolved 👍 
I can see examples in go-micro itself, is anyother repository i can find examples
