### ISSUE TITLE
Cannot register HTTP broker with Kubernetes plugin

### ISSUE THREAD

**Issue by twking7** [micro/go-micro#137]
First off, thanks for making this library!

If you try to use the HTTP broker to subscribe to a topic in a Kubernetes cluster, you get this error:

```
{
  "reason": "FieldValueInvalid",
  "message": "Invalid value: \"micro.mu/selector-topic:MyTopic\": name part must match the regex ([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9] (e.g. 'MyName' or 'my.name' or '123-abc')",
  "field": "metadata.labels"
},
```

I traced it back to this line: https://github.com/micro/go-micro/blob/master/broker/http_broker.go#L432

When you call `Register` on the registry for kubernetes, it uses the service's `Name` to populate the metadata keys. Unfortunately, adding the colon in the http broker violates the regex kubernetes uses.

I think a simple fix could be to change the `:` to a `.` or remove it entirely. I can make the PR if you want.

**Comment by asim** [comment]
This issue is kubernetes registry related rather than with the http broker. Kubernetes is enforcing constraints on values. The http broker should not have to constrain its formatting for that. The kubernetes registry should validate service names and change where appropriate.

Please file the issue against https://github.com/micro/go-plugins rather than go-micro since its kubernetes registry related.
