### ISSUE TITLE
"importing 'github.com/go-git/go-git/v5'" introduced MegaByte size dependences

### ISSUE THREAD

**Issue by masknu** [micro/go-micro#1641]
https://github.com/micro/go-micro/blob/fccab8ad27d13cc366180bbcaa9c1341b37b8b78/runtime/local/git/git.go#L12

"go-git/v5" depends on "go-billy/v5" which depends on "go-git-fixtures/v4", and go-git-fixtures includes massive .tgz files in it.
It takes too long to build a micro project due to downloading these files.

**Comment by crufter** [comment]
@masknu we will look into this! Thanks

**Comment by vtolstov** [comment]
yes, this is really bad thing

**Comment by mcuadros** [comment]
go-git-fixtures it's a test dependency of go-git. The tgz files are inside of the zip created by proxy.golang.org even when they do not need it since they are embedded in a data file.

The file is 47mb `https://proxy.golang.org/github.com/go-git/go-git-fixtures/v4/@v/v4.0.1.zip` and takes around 8s, the server doesn't look super fast, either. So I agree it's not convenient, even more, when it's a test dependency.

What is even worst is that you have as well the go-git-fixtures from the old org `src-d`, so you have the package twice.

From go-git org, we will try to find a solution to this problem. Feel free to open an issue.

**Comment by vtolstov** [comment]
@mcuadros thanks! i think that best of all - create dedicated test repo with fixtures.

**Comment by vtolstov** [comment]
fixed
