### ISSUE TITLE
app configuration

### ISSUE THREAD

**Issue by mkozjak** [micro/go-micro#190]
What is a preferred way to parse configuration (json/ini/whatever?) for go-micro services?
Any recommendations?
Do we just use cobra or something similar or can we reuse or combine something with go-micro?

Can we somehow avoid something like this? https://github.com/mkozjak/mockster/blob/master/main.go#L26

Or should we just use Consul for configuration?

Thanks.

**Comment by asim** [comment]
Please use the slack for discussion. Issues are used for bugs. I believe I've mentioned this before. http://slack.micro.mu/

Micro provides the ability to set flags/env vars and act on them. It otherwise has no opinion about configuration. Deploy configuration is largely driven by flags and env vars. App configuration more focused on what the application itself needs for business logic can be driven by anything.
