### ISSUE TITLE
Add ability to retry initial registry connection and register attempt

### ISSUE THREAD

**Issue by autodidaddict** [micro/go-micro#192]
In many testing scenarios, pipelines might be using tools like `docker compose` to spin up an ecosystem (or a subset of one) for acceptance and integration testing. While docker compose allows you to configure the _order_ of container startup, it doesn't have the ability to "wait" for a container to reach a steady/healthy state.

As such, it would be incredibly useful if we could supply a flag like `--registry_retries=5` to the application when it starts that will employ an exponential backoff timer and retry its initial registration. This would allow an app to start and retry while `consul` might be starting in another container asynchronously.

This has a number of really valuable benefits to enterprises that employ regular and automated acceptance testing by deployment to clusters or through docker compose.

**Comment by auwtch** [comment]
Just crash and restart.
https://docs.docker.com/compose/compose-file/#restart_policy

**Comment by asim** [comment]
Looking at this issue and the codebase I'm not really sure how to deal with it or whether I agree with the request. It's a tough one. 

In the code base we provide a simple default micro.Service implementation that calls register once on start and bails if there's an error https://github.com/micro/go-micro/blob/master/service.go#L114. I'm of the mind that this should probably be kept simple with a "fail fast" methodoloy. Because this is such a simple implementation of the micro.Service interface, you do have the option of defining your own service implementation that includes various extra bits of functionality like registry retries.

As @DenisNeustroev points out docker compose has a restart policy as do pretty much most process managing tools. Bailing out seems like the easiest thing to do. Retries do not guarantee successful execution, I would equate it to much like a time.Sleep behaviour used in tests as a hack. It's a hack for a specific issue here. 

A more appropriate solution would perhaps be to use BeforeStart option to check if consul is up before actually proceeding.

```
micro.NewService(
    micro.BeforeStart(func() error {
        var gerr error
        for i := 0; i < 3; i++ {
            if err := checkConsul(); err != nil {
                gerr = err
                backoff()
                continue
            }
            // success
            return nil
        }
        return gerr
    }),
)
```

While I know there's this mentality of cloud native/distributed systems being fault tolerant, it's also about understanding where it makes sense to build in that functionality. In the case of initial start and registration I feel that checking before starting and then failing fast if something happens along with a retry policy in a process manager makes the most sense.

**Comment by asim** [comment]
Closing as I don't think we're looking to solve this problem internally right now.
