### ISSUE TITLE
 The difference between v2 and v3

### ISSUE THREAD

**Issue by brightshin** [micro/go-micro#1958]
Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

Why is there no service.go and  micro.go file in the V3 go-micro directory, What are the best practices regarding V3

**Comment by asim** [comment]
V3 Redesign rationale https://github.com/m3o/dev/issues/269

Go-micro v3 is simply a standard library for microservices. You can get the same functionality expected from using the client/server directly. Otherwise we've moved the "framework" to be micro itself. See micro/services repo for example usage.
