### ISSUE TITLE
Random client transport fail

### ISSUE THREAD

**Issue by tudurom** [micro/go-micro#198]
I have the following code in my program:

```go
req := client.NewRequest("xmc.srv.account", "SessionsService.Login", &session.LoginRequest{
	ClientId:     username,
	ClientSecret: password,
})
rsp := session.LoginResponse{}
err := client.Call(context.Background(), req, &rsp)
```

Consul agent is started in dev mode, the service is up and running, no problems with that.

The problem is that the client request often fails.

Sometimes it gives the expected result:

```json
{"id":"xmc.srv.account.SessionsService.Login","code":401,"detail":"client_secret incorrect","status":"Unauthorized"}
```

And sometimes the request fails:

```json
{"id":"go.micro.client.transport","code":500,"detail":"404 Not Found: 404 page not found\n","status":"Internal Server Error"}
```

I noticed that I get the same result with `micro query`.

I tried restarting the server and consul (I stopped the server, then I stopped consul. Then I started consul and then the server). Same thing happens.

**Comment by asim** [comment]
This is very difficult from the information you've given. It feels less like a go-micro issue and more of a deployment or transient problem. 

Looking at the request failure. The id go.micro.client.transport implies a problem either when writing the request https://github.com/micro/go-micro/blob/master/client/rpc_codec.go#L123 or reading the response https://github.com/micro/go-micro/blob/master/client/rpc_codec.go#L131. I'm going to say it's likely when getting a response since the error code of 500 which we set does not match the detail provided of "404 Not Found: 404 page not found\n". 

The error "404 Not Found: 404 page not found\n" is not set anywhere within go-micro. It implies that whatever you are talking to is not a go-micro service. How are you running your account service? Is it an rpc service created and run in the default manner? Is there any intermediary proxy? Are you doing something unique? 

For further debug assistance you'll need to include more information but I would prefer you do this in the Slack rather than here as this is not a bug in go-micro itself but a usage issue.

**Comment by asim** [comment]
I found your code. Your exact problem is this https://github.com/xmc-dev/auth-srv/blob/master/main.go#L32. You are registering your service with the same name as the account service. So you end up calling your web service with an rpc request rather than the account service.

**Comment by tudurom** [comment]
that's a massive derp achieved by using `goimports` and not looking at the output. Thank you for your help!
