### ISSUE TITLE
micro v2

### ISSUE THREAD

**Issue by lefeck** [micro/go-micro#2161]
go 1.16  panic: qtls.ConnectionState not compatible with tls.ConnectionState micro v2

**Comment by dh1tw** [comment]
update your dependencies

**Comment by lefeck** [comment]
Is it necessary to lower the version of go to solve it? I saw some people say that it is supported by go below 1.15.&nbsp;How to solve above go 1.15?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "asim/go-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 晚上10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [asim/go-micro] micro v2 (#2161)





 
update your dependencies

**Comment by dh1tw** [comment]
go version 1.15 or newer is actually required in order to resolve this issue. The underlying lib lucas-clemente/quic-go#2614 has been fixed already some time ago and made compatible with go version 1.15. So, basically all you need is to update your dependencies - either by bulk `go get ./...` or individually `go get my-package`. Afterwards you should update your `go.mod` file with `go mod tidy`. I hope this is enough of a pointer to get get your rolling again.
