### ISSUE TITLE
[FEATURE] Starter Template Generator

### ISSUE THREAD

**Issue by asim** [micro/go-micro#2220]
Go micro used to be part of the Micro toolkit. The toolkit had many features including a cli, template generator and API gateway. It would be useful to readd some of these as standalone utilities.

If anyone would like to contribute a go-micro starter template or generator we welcome it.

**Comment by AuditeMarlow** [comment]
I'm currently working on [Gomu](https://github.com/AuditeMarlow/gomu), a CLI helper tool for developing Go Micro projects. I've taken some inspiration from Micro's CLI tool in the initial design. I've been adding features that the Micro CLI tool doesn't have, such as Jaeger integration, Skaffold file generation and a continuous build and run command. Perhaps we can combine efforts somehow?

**Comment by asim** [comment]
Yea that sounds interesting and the tool you're creating looks promising. What's your ideal way to combine efforts here?

**Comment by AuditeMarlow** [comment]
I don't really have any ideal way to combine efforts in mind. Keeping the feedback loops short should definitely help though. I'm willing to put in the work to (partially) migrate Gomu to Go Micro if that's preferable. I'm not entirely sure how this should be done, so it'd be helpful if you could give me some feedback.

I think initially my plan was to create a PR with a CLI for project generation and stuff. I ended up creating a separate project for it due to my lack of experience in Go, as well as having trouble figuring out how to integrate a Go Micro CLI tool. Micro has this concern pointed out in a pretty straight forward manner (a `main` package in the root of the project). Go Micro takes another approach and I'm having trouble adjusting to that.

**Comment by asim** [comment]
I think something like `github.com/asim/go-micro/cmd/gomicro` would make sense so we have a `$ gomicro ` command. Equally gomu is a nice shorthand. The naming aside, I think a package in cmd/ which is a `package main` will work because someone can just do `go get github.com/asim/go-micro/cmd/gomu` and use the CLI tool as they wish.

One thing I just don't want to do is slowdown your development while its a WIP. This project I'm largely just managing PRs for now but not yet adding anyone to the maintainer list. So it's your choice if you'd like to keep doing it in your own repo for now and then PR in or just make subsequent PRs as and when you like.

**Comment by AuditeMarlow** [comment]
Thanks for the feedback and insights. I think I'll keep my own repo for the time being until I'm feeling confident enough about the tool to submit a v1 PR to Go Micro.
