### ISSUE TITLE
NATS broker seems to be looking for Consul

### ISSUE THREAD

**Issue by EwanValentine** [micro/go-micro#223]
Hi there,

I have this repo: https://github.com/EwanValentine/shippy-email-service

I'm using mdns as the registry locally, and I'm trying to spin up a NATS listener using the broker plugin. I've imported the NATS broker plugin, and the mdns plugin (although I'm not sure I need to do this, as I haven't in other services using mdns?). But I'm getting the following output, when I run:
```
docker run --net="host" \
		-p 50054 \
		-e MICRO_SERVER_ADDRESS=:50054 \
		-e MICRO_REGISTRY=mdns \
		-e MICRO_BROKER=nats \
		-e MICRO_BROKER_ADDRESS=:4222 \
		email-service
```

```
2017/12/26 09:29:02 Broker Listening on [::]:36739
2017/12/26 09:29:02 Put http://127.0.0.1:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2017/12/26 09:29:02 Listening on [::]:50054
2017/12/26 09:29:02 Registering node: go.micro.srv.email-3578adec-ea1f-11e7-841a-563e0939f25a
```

The service seems to spin up correctly, but the broker's trying to register with Consul? 

Cheers in advance!

**Comment by asim** [comment]
The problem is that you're calling Init on a service then using the default broker directly with the import "github.com/micro/go-micro/broker". This doesn't work. Calling service.Init initialises the command line and plugins for the service and its internals, not everything else. 

If you want to initialise defaults you need to call Init in github.com/micro/go-micro/cmd. If you want to use a service then it's better to call service.Init and then use the broker that's been setup in there. 

```
service.Server().Options().Broker
```

**Comment by EwanValentine** [comment]
So for a service, I'd just call `myBroker := srv.Server().Options().Broker`, then use `myBroker.Publish(...)` etc? That makes sense now. Cheers and happy holidays!
