### ISSUE TITLE
[FEATURE] Tracing package

### ISSUE THREAD

**Issue by asim** [micro/go-micro#2257]
Distributed tracing is a core concern which we've avoided to define. We have some wrappers but we could likely define an interface. We avoided it just because there was a lot of back and forth in the opentracing/opentelemtry/openconcensus space.

A past implementation I wrote looked like

```
type Trace interface {
	Close() error
	// New span with certain fields preset.
	// Provide parent span if you have it.
	NewSpan(*Span) *Span
	// Collect spans
	Collect(*Span) error
	// Name
	String() string
}

type Span struct {
	Name      string        // Topic / RPC Method
	Id        string        // id of this span
	TraceId   string        // The root trace id
	ParentId  string        // Parent span id
	Timestamp time.Time     // Microseconds from epoch. When span started.
	Duration  time.Duration // Microseconds. Duration of the span.
	Debug     bool          // Should persist no matter what.

	Source      *registry.Service // Originating service
	Destination *registry.Service // Destination service

	sync.Mutex
	Annotations []*Annotation
}

type Annotation struct {
	Timestamp time.Time // Microseconds from epoch
	Type      AnnotationType
	Key       string
	Value     []byte
	Debug     map[string]string
	Service   *registry.Service // Annotator
}
```

There's also a different version currently in debug/trace https://github.com/asim/go-micro/blob/master/debug/trace/trace.go

**Comment by FarhanSajid1** [comment]
I believe this is related:
https://github.com/asim/go-micro/issues/2405

**Comment by FarhanSajid1** [comment]
I believe now OpenTelemetry is the single tracing package, opentracing and opencensus have merged to form opentelemetry. I think just having a single OpenTelemetry package makes sense?

**Comment by refs** [comment]
@FarhanSajid1 Correct. We actually switched over to OpenTelemetry at ownCloud. The tooling is great, and it is convenient to have all functionality centralized. This can be started right away using OT tooling 👍

**Comment by refs** [comment]
I believe sticking to @asim interface could be good enough. There are a few things to address, tho. One of them is trace serialization. A trace should be able to "travel" with the request, so that the service on the other end can add more spans onto it (which is the conceptual issue @FarhanSajid1 is having). For that OpenTelemetry defines a [propagation](https://github.com/open-telemetry/opentelemetry-go/tree/main/propagation) package, which could be used as inspiration.

I will look if creating a trace with an existing TraceID in OpenTelemetry allow services to continue to report spans, and the OpenTelemetry (OT) collector would display them correctly. I'll be implementing this interface for an OT concrete type and should be opening a PR soon.

**Comment by plunkettscott** [comment]
Any luck on starting a PR for this, @refs? Currently investigating OpenTelemetry with go-micro now.

**Comment by refs** [comment]
@plunkettscott I do have some stashed changes but they're not worth opening a PR with. I recently switch jobs so my time is reduced currently, but feel free to take over if you'd like!
