### ISSUE TITLE
Unable to handle errors serving request

### ISSUE THREAD

**Issue by liilac** [micro/go-micro#236]
First of all, apologies if this is a duplicate of #234; I'm not sure whether the issue is talking about the same sort of thing.

Currently, there is no way to handle errors that occur in `server.serveRequest()`, as used [here](https://github.com/micro/go-micro/blob/6246fa2bcb781619ab295df972a65f092124a8df/server/rpc_server.go#L110).

This means that some kinds of errors, like input (`req` parameter) that cannot be unmarshalled into the correct type, cannot be captured or otherwise handled.

I am particularly interested in logging errors to an external service, which I cannot do without being able to somehow capture the error.

Would it be possible to add functionality to allow us to perhaps wrap this error handling functionality, similar to the existing wrapper functions?

Thanks!

**Comment by asim** [comment]
This is a low level error which makes capturing it difficult. It's also an implementation detail of the rpc server. I'm not sure wrappers are the best solution. We may just need to provide a better way to return an error to the client.

**Comment by liilac** [comment]
Okay, thanks.

**Comment by asim** [comment]
Ok so I just want to respond and then close this issue. 

The log line below serveRequest makes use of the the micro global logger https://github.com/micro/go-log. You can set this logger before startup and handle logging to an external service. Hope this resolves your issue. Otherwise there's currently no other way to capture serveRequest output.
