### ISSUE TITLE
Support for OpenCensus instrumentation

### ISSUE THREAD

**Issue by t-bast** [micro/go-micro#243]
I started experimenting with go-micro for my micro-services architecture, thanks for the very complete framework!

I'd like to find the best way to fit [OpenCensus](https://opencensus.io/) instrumentation on the RPC clients/servers. It requires passing around a SpanContext in calls between micro-services and retrieving this information when receiving a request to enrich it (a lot like the Zipkin tracing for which it looks like there is a plugin already).

I'm still new to the abstractions of the go-micro RPC part, so I'm finding it a bit difficult to figure out where I could fit this. Do you have suggestions on how I could achieve that?

Thanks!

**Comment by asim** [comment]
Thanks, contributions most welcome!

Go-micro has the concept of middleware through something called wrappers. They "wrap" the functionality of the client and server. I believe the best place to start would be the OpenTracing wrapper https://github.com/micro/go-plugins/blob/master/wrapper/trace/opentracing/opentracing.go. The zipkin plugin for trace is no longer relevant as it was for a different library which has now been deprecated. We will revisit creating an observability library at some point but I believe wrappers are the best place for this functionality.

I'm closing this issue because we don't really use issues for anything but bug tracking but feel free to open a PR to go-plugins to include something for opencensus.

**Comment by t-bast** [comment]
Sounds good, thanks for the pointers I'll have a look at the opentracing wrapper.
