### ISSUE TITLE
How do I properly allow overriding HTTP Transport's default Dial func?

### ISSUE THREAD

**Issue by sthetz** [micro/go-micro#263]
Hello!
I am very excited about go-micro and want to thank all the contributors for the great work you are doing. 

My business needs require using custom Dial function to communicate with microservices in my environment. Unfortunately I couldn't find how to do it properly, and came up with this quick and dirty hack: https://github.com/sthetz/go-micro/commit/95638e3ff433a85ec42b39c51ef577f62baaf69a

If I understand your architecture correctly, the proper way would be to use `transport.Option`/`transport.DialOption` to set the Dialer, but I couldn't figure out how to do that. I tried adding a field to these structs and exposing setter functions to set that field, but in `func (h *httpTransport) Dial(addr string, opts ...DialOption) (Client, error)` the `httpTransport` didn't have the Dialer that I set. 

Am I right in assuming that something like this wouldn't work at the moment?

```
micro.NewService(
  micro.Transport(
    transport.NewTransport(
      transport.WithDialer(customDialer), // would-be setter function for overriding the dial
    ),
  ),
)
```

**Comment by asim** [comment]
What's the reason for overriding the dialer?

**Comment by sthetz** [comment]
So people could use stuff like https://github.com/rs/dnscache and https://github.com/libp2p/go-reuseport. I do understand that it's very uncommon, but clientside DNS caching helps mitigate networking issues in my particular setup.

**Comment by asim** [comment]
In terms of something like dns caching I would say you should handle this higher up. We use service discovery to resolve names to addresses, by the time the address is passed into the transport we're expecting it's been resolved. Either setting fixed ips in discovery or writing a selector which does the lookup would make sense.

Otherwise, the hack is close but not an ideal solution.

We would define `Dialer` as an interface and then accept that as an option to the transport. Still preserving the transport interface. The transport would then use the dialer to create the client.

**Comment by sthetz** [comment]
You're right, handling dns caching via custom selector plugin is a much more straightforward solution.
Thank you for a swift response and valuable advice.
