### ISSUE TITLE
client GRPC and client.Retries(5) will cause timeouts ?

### ISSUE THREAD

**Issue by gstarikov** [micro/go-micro#277]
Hello,

```
import (
	"github.com/micro/go-micro"
	"github.com/micro/go-grpc"
	"github.com/micro/go-micro/selector/cache"
	clientGRPC "github.com/micro/go-plugins/client/grpc"
)

...

	clientGRPClocal := clientGRPC.NewClient( client.PoolSize(10), client.Selector(cache.NewSelector(cache.TTL(time.Second))), client.Retries(5) )

		VS

	clientGRPClocal := clientGRPC.NewClient( client.PoolSize(10), client.Selector(cache.NewSelector(cache.TTL(time.Second))) )
```

in first case (when set client.Retries(5)) we catch timeouts (default 5 sec) at 100% of the requests,
at second case (without client.Retries(5)) every thing works as should be.
I can not understand what went wrong and why.

is it our fault or bug in go-micro?

**Comment by asim** [comment]
Client retries dictates the number of retry attempts, this is separate from the overall request timeout. There's also an exponential backoff mechanism built in which is why 5 attempts is not the same as 5 seconds. A client should retry until the request timeout expires but we shouldn't do this at the same interval because multiple clients may attempt this, instead a randomly jittered and exponential backoff is required. So client.Retries(5) may not yield 5 retry attempts in 5 seconds.

**Comment by gstarikov** [comment]
yes, but service to which we trying to connect is fully available. in case of without client.Retries(5) grpc client works fine, but in case of client.Retries(5) there will be timeout in any request.
steps to reproduce:
- prepare grpc client with client.Retries
- make request and there will be timeout
- prepare grpc client without client.Retries
- make request
- it works fine

**Comment by gstarikov** [comment]
Yes you are right, it's my fault. we are using http 500 code in case of some business exceptions instead of http 200 code
