### ISSUE TITLE
visibility for client to registered services

### ISSUE THREAD

**Issue by magaldima** [micro/go-micro#284]
I'm interested in having a `Client` have some visibility into the available "registered" services. Is there any easy way to expose this and/or add this to the `Client` interface without knowing beforehand the service name?

This is essentially analogous to a `Kubernetes Discovery Client`.

**Proposal:**
Modify the `Service` interface to expose a `Discovery` interface.
```
// Service is an interface that wraps the lower level libraries
// within go-micro. Its a convenience method for building
// and initialising services.
type Service interface {
	Init(...Option)
	Options() Options
	Client() client.Client
	Server() server.Server
	Run() error
        Discovery() discover.Discovery
	String() string
}
```

The Discovery interface should be defined as:
```
// Discovery provides an interface to find and watch Services
type Discovery interface {
	GetService(string) ([]*registry.Service, error)
	ListServices() ([]*registry.Service, error)
	Watch(...registry.WatchOption) (registry.Watcher, error)
}
```

Finally, this means that the `Registry` interface should be:
```
// The registry provides an interface for service discovery
// and an abstraction over varying implementations
// {consul, etcd, zookeeper, ...}
type Registry interface {
	Register(*Service, ...RegisterOption) error
	Deregister(*Service) error
	discovery.Discover
	String() string
	Options() Options
}
```

**Alternative:**
My other alternative to this, would be to add a simple API to my service that enables a client to ping a service (essentially a way to say: "if you exist, send me an ack"). I realize this is very similar to a /health endpoint, but instead of the purpose of tracking the health of a service, I want to track the existence of registered services available to a particular micro client.

**Comment by asim** [comment]
So micro is a development framework that abstracts away the details of distributed systems, promoting a microservice architecture pattern through code. Each package provides underlying functionality you would expect. Including service discovery via the [Registry](https://godoc.org/github.com/micro/go-micro/registry#Registry). 

We make it a point to build upon each abstraction to provide a simpler interface at the top-level. It's very unlikely we make Discovery something at the top level since this shouldn't be a client concern, if anything the client should only deal with calling something by name and that's it. The client implementation makes use of the registry to find the addresses of a service name but from a developer perspective the client is just used to call a service by name.

In the case of visibility, all services have the ability to see all the other services available in the registry. Namespacing and policy enforcement to restrict this would be a higher level or external concern. From the view point of a service or this framework, it's focused on communication itself.

You can get the list of services via the client registry with `service.Client().Options().Registry`. Then call the `ListServices()` method.

In your alternative approach. Every service includes a `Debug` endpoint including `Debug.Health` and `Debug.Stats`. We could optionally include a `Debug.Ping` endpoint but it would basically do the same thing as the health endpoint. My suggestion would be to perhaps use the client to list services and then call the health endpoint. There's nothing built in to the client to do this.

Hope that answers the question.

**Comment by magaldima** [comment]
@asim Thank you! This more than answers my question and provides me with more than enough for my purposes. Also I agree with you about your concerns.

If I can access the Client()'s `Registry`, is it also a potential concern that I can directly call `Register()`?

**Comment by asim** [comment]
From my standpoint it's not a concern, it's part of the configuration. It's difficult to obfuscate this from the user when they need the registry to do service discovery. Access control should really be dictated by an external source.
