### ISSUE TITLE
Server Handle() method error never handled

### ISSUE THREAD

**Issue by gillesfabio** [micro/go-micro#287]
The RPC server `Handle` method error is never handled. The generated `RegisterServiceHandler` function silently bypasses the `s.Handle()` error return ([here](https://github.com/micro/protoc-gen-micro/blob/master/examples/greeter/greeter.micro.go#L90)). And so [here](https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L155) and [here](https://github.com/micro/go-micro/blob/master/server/rpc_service.go#L161). That means it can be very time consuming to debug a server handler registration error. 

`RegisterServiceHandler` should handle this error with an explicit error return or a `panic`.

**Comment by asim** [comment]
Please file your issue under the protoc-gen-micro project since this is related to the code generation. Feel free to PR a fix. This seems fairly straightforward, we should just return an error. The change in the function signature should not break anything considering there was no pre-existing return type.
