### ISSUE TITLE
RPC call got an EOF error after shutdown the service

### ISSUE THREAD

**Issue by imneov** [micro/go-micro#314]
When we use this code( https://github.com/micro/go-micro/blob/master/function.go#L55L57) tells the server to wait for requests to finish before exiting, but when all sync.WaitGroup is done.

1. server and client conn't finish close socket
2. client con't refresh server nodes

That cause some error below when the server ends:

```
2018/10/10 18:20:04 error, {"id":"go.micro.client.transport","code":500,"detail":"EOF","status":"Internal Server Error"}
2018/10/10 18:20:04 error, {"id":"go.micro.client.transport","code":500,"detail":"EOF","status":"Internal Server Error"}
2018/10/10 18:20:04 error, {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 192.168.99.1:53306: connect: connection refused","status":"Internal Server Error"}
2018/10/10 18:20:04 error, {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp 192.168.99.1:53306: connect: connection refused","status":"Internal Server Error"}
```
And I add a sleep time to fix it.
https://github.com/imneov/go-micro/compare/master...imneov:patch-1

**Comment by asim** [comment]
You're seeing this error due to a connection being closed by the server when the client is maintaining a connection pool and because other connection attempts are being made because of node caching by the selector. A 1 second sleep is a hack to solve the problem but ideally we should just be able to deal with these errors at a higher level e.g with retries.

**Comment by asim** [comment]
No response in 10 days. Closing.
