### ISSUE TITLE
Avoid registering a service

### ISSUE THREAD

**Issue by paraths26** [micro/go-micro#365]
Is there a way, a service can avoid registering itself? I have a go-web service running in a docker container and there is a registrator on the same machine to register the service separately, which results into two consul nodes for the same service. If we can set some flag value which tells service.Run() to not  to call Register(). 
Thanks.

**Comment by asim** [comment]
Go Web is a slim wrapper around go-micro and net/http to register http based services in discovery. If you don't need this functionality you should really not be using go-web. 

In the event you want to use it and not register, I would advise you to use the plugin for the noop registry https://github.com/micro/go-plugins/tree/master/registry/noop. 

Otherwise, what you're doing makes no sense because the whole reason for the existence of go-web is to register services.
