### ISSUE TITLE
latest go-micro errors.BadRequest() returning HTTP 200 to client

### ISSUE THREAD

**Issue by rampredd** [micro/go-micro#369]
I simply do the following

func (gateway *Gateway) Search(ctx context.Context, req *gw.QueryRequest, rsp *gw.QueryResponse) error {
        log.Print("Received Gateway.Search request")
        return errors.BadRequest("gateway", "please enter mandatory fields")
}

func main() {
        service := micro.NewService(
                micro.Name("go.micro.api.gateway"),
        )

        // Init will parse the command line flags. Any flags set will
        // override the above settings. Options defined here will
        // override anything set on the command line.
        service.Init()

        // register gateway handler
        gw.RegisterGatewayHandler(service.Server(), &Gateway{})
        if err = service.Run(); err != nil {
                common.PrintError(err)
        }
}

CURL result expected HTTP 400 BUT:

$ curl -i -H 'Content-Type: application/json' -d '{}' "http://localhost:8080/gateway/Search" 
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization
Access-Control-Allow-Methods: POST, GET, OPTIONS, PATCH, PUT, DELETE
Content-Length: 4
Content-Type: application/json
Date: Mon, 07 Jan 2019 06:15:24 GMT

**Comment by asim** [comment]
I know what the problem is. I just need to determine the best way to solve it. 

We're moving certain request data into headers so the body can be processed as raw json, proto, bytes or whatever else. The current codecs don't take this into account. Either the codec needs to encode this logic or it needs to be done in the client. I'm planning to do it in the client first. Will have a fix later today.

**Comment by asim** [comment]
Pushed a fix. Please test.

**Comment by inigofu** [comment]
I have uptated my go-micro version, but still facing the same problem.

**Comment by inigofu** [comment]
I did no change anything in my code. I update to golang 1.11.4 some days ago and start facing this problem. I thought it was because of golang version change. I downground it but still have the problem. Yesterday I saw this issue and try to update go-micro to latest version with go 1.11.4 installed, but I still have the same problem.

**Comment by asim** [comment]
I'm testing it right now and it works.

`go get -u github.com/micro/micro` to update all your code.

**Comment by inigofu** [comment]
After several trials I found that:

Case a) running micro --registry=mdns api and calling http://localhost:8080/rpc 
- If there is no error I get a http 200 and a response json
- If there is an error I get a http 200 and a null json

Case b) running micro --registry=mdns web and calling http://localhost:8082/rpc 
- If there is no error I get a http 200 and a response json
- If there is an error I get an error code and an error json

Case b is working as it should.

**Comment by asim** [comment]
You're now discussing a completely different endpoint which does not use the same code. Please file this as a separate issue in the micro repo. Your initial issue should be fixed if you update all your dependencies.
