### ISSUE TITLE
Server register error: Unexpected response code: 500 (CheckID "service:broker-xxx" does not have associated TTL))

### ISSUE THREAD

**Issue by SgtDaJim** [micro/go-micro#440]
part of my code:
```go
brokerOption = micro.Broker(
	broker.NewBroker(
		broker.Addrs(fmt.Sprintf("%s:%d", advertiseIP, brokerPort)),
	),
)
......
service := micro.NewService(
		micro.Name("xxx"),
		micro.Version("latest"),
		micro.Server(
			server.NewServer(
				server.Address(fmt.Sprintf("%s:%d", advertiseIP, transportPort)),
				server.Name("xxx"),
				server.Advertise(fmt.Sprintf("%s:%d", advertiseIP, transportPort)),
			),
		),
		brokerOption,
		transportOption,
		micro.Registry(
			consul.NewRegistry(
				registry.Addrs("xxx"),
				consul.TCPCheck(time.Second*30),
			),
		),
	)
```

Then the server can register, but the broker failed.
And the problem seems to cause by consul.TCPCheck()
Please have a look.

**Comment by printfcoder** [comment]
I try this usage, it works fine. wondering this problem is still existed?

**Comment by SgtDaJim** [comment]
still does. everything will work fine if i remove `consul.TCPCheck(time.Second*30)`

**Comment by hb-chen** [comment]
micro web still have this issue, version v1.9.1
and will exit
```
	service := web.NewService(
		web.Name("go.micro.web.test"),
		web.Version("latest"),
		web.Registry(consul.NewRegistry(
			consul.TCPCheck(time.Second*5),
		)),
	)
```

```
2019/08/28 14:47:52 Listening on [::]:54095
2019/08/28 14:47:52 Unexpected response code: 500 (CheckID "service:xxx" does not have associated TTL)
exit status 1

```

**Comment by hb-chen** [comment]
add RegisterTTL option time.Duration(0) will be ok.
```
web.RegisterTTL(time.Duration(0)),
```

**Comment by linzhoulxyz** [comment]
same issue, version v1.10.0  when use consul.TCPCheck()  

web can use 
 `web.RegisterTTL(time.Duration(0))`
to fixed 

service can use
`micro.RegisterTTL(time.Duration(0))`
to fixed

**but** broker has no way to set TTL time.Duration(0), because in http_broker.go, registerTTL is unexported, and no method can set it's value 

https://github.com/micro/go-micro/blob/6f2a8298ef039fd046107171dc74eb45a2b36d52/broker/http_broker.go#L65-L70

https://github.com/micro/go-micro/blob/6f2a8298ef039fd046107171dc74eb45a2b36d52/broker/http_broker.go#L223-L233

https://github.com/micro/go-micro/blob/6f2a8298ef039fd046107171dc74eb45a2b36d52/broker/http_broker.go#L258-L274

@printfcoder  please help me to check the problem, thank you
