### ISSUE TITLE
gossip data race from last commit to gossip registry

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#540]
this is single service setup
```
==================
WARNING: DATA RACE
Write at 0x00c0084ac580 by goroutine 91:
  github.com/micro/go-micro/registry/gossip.delServices()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/util.go:122 +0x1fd
  github.com/micro/go-micro/registry/gossip.(*gossipRegistry).run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/gossip.go:648 +0x7fe

Previous read at 0x00c0084ac580 by goroutine 153:
  github.com/micro/go-micro/registry/cache.(*cache).update()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/cache/rcache.go:190 +0x1fa
  github.com/micro/go-micro/registry/cache.(*cache).watch()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/cache/rcache.go:377 +0xaa
  github.com/micro/go-micro/registry/cache.(*cache).run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/cache/rcache.go:337 +0x52c

Goroutine 91 (running) created at:
  github.com/micro/go-micro/registry/gossip.NewRegistry()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/gossip/gossip.go:833 +0x2f8
  main.(*ucmd).Before()
      /home/vtolstov/devel/projects/centralv2/cmd.go:310 +0x12bb
  main.(*ucmd).Before-fm()
      /home/vtolstov/devel/projects/centralv2/cmd.go:186 +0x4b
  github.com/micro/cli.(*App).Run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/cli/app.go:242 +0xa9e
  main.main()
      /home/vtolstov/devel/projects/centralv2/cmd.go:463 +0xab

Goroutine 153 (running) created at:
  github.com/micro/go-micro/registry/cache.(*cache).get()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/cache/rcache.go:160 +0x37c
  github.com/micro/go-micro/registry/cache.(*cache).GetService()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/registry/cache/rcache.go:383 +0x5f
  github.com/micro/go-micro/client/selector.(*registrySelector).Select()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/selector/default.go:52 +0x19b
  github.com/micro/go-micro/client.(*rpcClient).next()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_client.go:313 +0x2d8
  github.com/micro/go-micro/client.(*rpcClient).Call()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/client/rpc_client.go:330 +0x1ff
  github.com/micro/go-plugins/wrapper/breaker/gobreaker.(*clientWrapper).Call()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-plugins/wrapper/breaker/gobreaker/gobreaker.go:50 +0x459
  unistack.org/centralv2/common.(*latestVersionWrapper).Call()
      /home/vtolstov/devel/projects/centralv2/common/version.go:23 +0x250
  github.com/micro/go-micro.(*clientWrapper).Call()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/wrapper.go:32 +0x114
  unistack.org/centralv2/service/auth/authpb.(*authService).Crt()
      /home/vtolstov/devel/projects/centralv2/service/auth/authpb/auth.micro.go:73 +0x1b4
  unistack.org/centralv2/mtls.(*Config).getCerificate()
      /home/vtolstov/devel/projects/centralv2/mtls/mtls.go:127 +0x728
  unistack.org/centralv2/mtls.(*Config).loop()  
      /home/vtolstov/devel/projects/centralv2/mtls/mtls.go:178 +0xa4
==================

**Comment by milosgajdos** [comment]
Thanks for reporting @vtolstov. Could you share some code with us so we can reproduce the race locally? 

From what I can see and assumed based on the `stacktrace` is that your code uses 2 registries: 
* `gossip`
* `cache`

I'm guessing that you're passing [a pointer to] a service object between these registries which themselves spin and run their own goroutines which are uncoordinated in terms of access to the passed around service object which then in turn gets modified in `util.go` in order to remove the expired `registry.Node` from the `registry.Service` object and boom, race happens.

An example piece of code would help us understand the race behaviour better other than making random assumptions we're having to do at the moment.

**Comment by asim** [comment]
The previous code was making a copy of each service https://github.com/micro/go-micro/commit/c0a628d65b024d1c1a95f9e6a0419d356da1e973#diff-34e5c227e729424d384c276902b69ab1L121 which is what was preventing the data race.

**Comment by milosgajdos** [comment]
Yes, that is correct, but that was the reason why the original code wasn't deleting the the nodes of the service that was pushed downstream to [publish](https://github.com/micro/go-micro/blob/master/registry/gossip/gossip.go#L657) because `u.Service` was never actually modified.

**Comment by vtolstov** [comment]
Cache us used by default via caching selector, yes you bring race removing copy of service data and returning pointer.

**Comment by milosgajdos** [comment]
Yep. Returning the copy, however, breaks the data consistency.

**Comment by asim** [comment]
Why does modifying the structure fix this the problem as opposed to creating a copy and setting that in the map? This feels weird because what's being published to the watcher should technically just be the thing to delete.

**Comment by milosgajdos** [comment]
> ...what's being published to the watcher should technically just be the thing to delete

I'm confused by this a bit. The service `Node`s are being deleted in the registry `update` loop [here](https://github.com/micro/go-micro/blob/master/registry/gossip/gossip.go#L647-L653). The modified service is then published in the [event](https://github.com/micro/go-micro/blob/master/registry/gossip/gossip.go#L657).

What I meant by "breaking data consistency" is if the selector (the client) refers to some data that is different from what the "server" refers to we've got a consistency issue. Correct me if I'm wrong, please as I might be missing something fundamental here.

**Comment by asim** [comment]
Ok yea there's a miscommunication here and misunderstanding because I haven't commented the code.

A watcher publishes the thing that is to be created, updated or deleted. Meaning if it publishes with a delete event it publishes the service with the nodes that are to be deleted. Not the updated copy of the service that should be used but the actual things that need to be removed. 

u.Service should not be modified. delServices should be returning a new copy services/nodes removed from the service and that new copy is whats placed into the local map/registry.

Which means your expectations from the Watch side were the expectations of getting an updated service that has deleted nodes, but that's not the expectation from how we were implementing it previously. We were expecting to receive the service which the nodes that are needing to be deleted.

See cache code. When it receives this delete event it expects the nodes that it should delete https://github.com/micro/go-micro/blob/master/registry/cache/rcache.go#L231

**Comment by milosgajdos** [comment]
If that's the desired behaviour then `util.go` change has definitely broken you've just described.

My assumption about what the event publish does was wrong -- I had the impression that the event was a post-action (a posteriori) "notification" about the action that has been taken on a service as opposed to what youre describing here.

**Comment by asim** [comment]
We want the Action to take plus the Delta for that action as opposed to being told what the Action "was" and what the new entity is. We probably need to comment the watcher to make this clear. This is my fault entirely.

**Comment by milosgajdos** [comment]
OK, I need to think this through as my mental model was very different from the actual behaviour. I will have to get properly familiar with this part of codebase.

I'm happy to revert the code to the original state, however that will break the `router` behaviour >_<

**Comment by asim** [comment]
We should revert and fix the router on Monday/Tuesday. Not urgent.

**Comment by milosgajdos** [comment]
Not sure what the `router` code should look like with the revert, though. The original change was done to get the router working "correctly". Might need another design discussion in that case. Will open a revert PR shortly.

**Comment by asim** [comment]
Guess it depends on what the expectation is for the router when it receives that delete event. Whether it's just registering the service in the registry or calling deregister which is probably what would work.

**Comment by vtolstov** [comment]
Thanks
