### ISSUE TITLE
micro command not found while GOPATH env is in $PATH

### ISSUE THREAD

**Issue by alirezastack** [micro/go-micro#618]
I have used [go-micro installation](https://micro.mu/docs/cli.html#install) instructions. It has been successfully installed. Now I dont have access to `micro` command in bash:

```
$ micro cli

Command 'micro' not found, but can be installed with:

sudo snap install micro

```

Now when I echo `$GOPATH`:

```
echo $GOPATH
/home/myuser/go
```

When I echo `$PATH` the below paths are present:

```
/home/myuser/go:/home/myuser/go/bin
```

Shouldn't I have access to `micro` command now? Why it is not recognized?

**Comment by milosgajdos** [comment]
Can you tell us the following: 
* what version of `go` you are using.
* do you have `go` modules turned on when getting the repo (this should be irrelevant to your question, but I'm asking it anyways)

Can you check if `micro` cli is in `$GOPATH/bin/micro`:
```
ls -l $GOPATH/bin/micro
```

Besides, this seems more like a [work] environment issue than a `go-micro` issue. I imagine if you join [micro slack](https://micro-services.slack.com) you might get faster help with local environment setup if need be.

Finally, next time, can you please makes sure you open the micro **toolkit** issue in https://github.com/micro/micro repo instead of in the **framework** (`go-micro`) repo. Thanks!

**Comment by alirezastack** [comment]
Sorry if question is not in the right place!

`go version:` go1.12.7 linux/amd64

How should I check for `go modules` state (new to the language)

Unfortunately it is not present in the `bin` folder:
```
ls -l $GOPATH/bin/micro
ls: cannot access '/home/myuser/go/bin/micro': No such file or directory
```

**Comment by milosgajdos** [comment]
All, right, something might be "broken" in your work environment. 

Can you try doing something like this:
```
export GO111MODULE=on
go get -u github.com/micro/micro
```

Alternatively, for more verbose output:
```
export GO111MODULE=on
go get -x -u github.com/micro/micro
```

If that does not work pop by in our [slack channel](https://micro-services.slack.com/) as I mentioned earlier. There might be more people to give you a hand.

**Comment by alirezastack** [comment]
@milosgajdos83 I cannot join to the work space. It gives error to contact work space administrator:

> Don't have an account on this workspace yet?
> Contact the workspace administrator for an invitation
> 

Can I have join link or something to join to the work space? if you could help how to join the work space that'd be great for my questions :)

I ran the command by the way after getting a long list of modules it gave the below error:

```
go: extracting golang.org/x/sys v0.0.0-20190726091711-fc99dfbffb4e
build github.com/micro/micro: cannot load github.com/micro/go-micro/cmd: cannot find module providing package github.com/micro/go-micro/cmd
```

**Comment by milosgajdos** [comment]
@alirezastack the link to our slack is on [here](https://micro.mu/slack/). Apologies for invalid URL earlier.

I don't quite understand how can you be getting this error:
```
build github.com/micro/micro: cannot load github.com/micro/go-micro/cmd: cannot find module providing package github.com/micro/go-micro/cmd
```

Since there is NO package called `cmd` under `github.com/micro/go-micro` 

Can you create a gist of output that captures the command you're attempting to run and the output somewhere?

**Comment by alirezastack** [comment]
@milosgajdos83 it is really weird that every time I run the same command I get a different result. [The first installation attempt](https://gist.github.com/alirezastack/e9a26dbcbb6134e7dfc853ea1704a075) and [the second installation attempt](https://gist.github.com/alirezastack/e7af9b903b2a3cf65f1c15fcca27ee04)

I don't know if this helps, but once I installed micro (well I assumed it is go-micro!) using `snap install micro` and then removed it using `snap remove micro`

**Comment by milosgajdos** [comment]
Very strange! Tbh, kinda running out of ideas here...I suspect some local workstation `go` setup shenanigans.

It seems the command in the second gist has succeeded then?

Also `snap` is some kinda Ubuntu command thing, no? I'd maybe uninstall `go` and installed the latest `go` from source and do the `go get -u...` thing again.

**Comment by alirezastack** [comment]
I appreciate for the work. I think it would be much easier to reinstall `golang` and proceed with `micro` installation again. I will update here.

**Comment by alirezastack** [comment]
Unfortunately reinstalling `go` from source and installing `go-micro` didn't help. I'm closing this issue as this seems work environment issue rather than `go-micro`.

**Comment by teract-ng** [comment]
Just in case anyone else run into the same issue, What fixed it for me, 
`export PATH=$PATH:$(go env GOPATH)/bin`
`export GOPATH=$(go env GOPATH)`

**Comment by ghost** [comment]
```
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)
```

worked for me thank you @teract-ng
