### ISSUE TITLE
Question about grpc clients and micro in general

### ISSUE THREAD

**Issue by dalu** [micro/go-micro#662]
The attractiveness of grpc is its many clients, in particular the usefulness for mobile frontends.
The android java client for instance is able to be autogenerated in the gradle build process.

What is the compatibility of go-micro with regular rpc clients?
Say I write my backend with micro and expose the grpc port in some way (which leads me to another question), is that possible and can I use the same proto file with slight modifications for the android or ios client to talk to the grpc port written with micro?

Then grpc-web, I see you have envoy somewhere in the whole stack. I take it grpc-web is working without issues?
I'm flirting with grpc because I'd like 1 way to define my services and not have to duplicate the data models on the client.
My yesterday's experiment with android studio and grpc on the client side and go and grp on the server side was successful, which I can't say for grpc-web, mainly because envoy is such a PITA but also various other reasons.
However when I write a service, I'd like to cover all the possibilities, web, mobile and eventually even desktop (which could be a web wrapper).

There is a pub/sub functionality in micro, how would that work with an e.g. android client?

**Comment by asim** [comment]
Go micro supports grpc as a protocol. We do not otherwise support the grpc ecosystem of tooling. Its up to the user to decide where that interaction should be. If micro's grpc client and server and used then they will be compatible with other grpc services. We use service name + method and translate those to grpc method calls.

In regards to multi platform. We want to eventually be on every platform but it will take to determine the best path for us to do this.

**Comment by dalu** [comment]
Ok and since the only client available currently is in Go...
Thank you for the response.
