### ISSUE TITLE
Expose way to get clients for broker/registry etc.

### ISSUE THREAD

**Issue by waeljammal** [micro/go-micro#678]
Right now all the abstractions are private and hidden away behind interfaces giving us no way to get access to the clients that are already connected. 

Eg. I have another library that wants to use consul and go micro has already created a connection, I should be able to retrieve that even if I have to cast it myself and use it. The same goes for things like Rabbit etc. Would save creating another connection when you can re-use an existing one.

I know it's not a good pattern when you can switch out what registry/broker etc. you are using but I think in most cases one you've chosen your stack and _ imported the registry/broker/etc. that you want to use you pretty much stick with that so doing something like ```registry.Client().(*consul.Client)``` should be fine.

Thanks

**Comment by asim** [comment]
You can access the registry via client options `client.Options().Registry`. We will however now provide the option to cast to the underlying consul client provided by the consul library. This makes no sense. Our abstractions are there for a reason. If you want to use consul create a new client for consul. Do not force us to leak underlying infrastructure, that's bad design.

**Comment by waeljammal** [comment]
Is there a way then to provide our own client to micro? I already stated it was bad design and I agree but looking at the code I saw no quick win. It's easy to say create your own client but when you have 1000's of distributed clients connecting to RMQ/Consul etc. in a multi tenant system Creating extra redundant connections is hard to swallow and puts a strain on resources. In some cases this is fine where it's not a persistent connection like an HTTP client, but in others it is an issue when it's something like a broker connection.

**Comment by asim** [comment]
This doesn't make sense in the case of micro. Micro is focused on micro services, meaning individual services and processes that maintain and manage their own connection to the underlying infrastructure. We're not expecting much else to be happening in those processes beyond running that microservice and using micro to interact with other services. If your needs go beyond that then you might be better of building something speicifc to your needs.

If you'd like to discuss specific issues rather than hypotheticals thats fine but in this scenario I find it hard to believe you have 1000s of connections to rabbitmq and consul. If that's the case then you have large scaling issues to deal with and you may want to offload much of these requirements to proxies.

**Comment by waeljammal** [comment]
Thanks will close the issue and find another solution.
