### ISSUE TITLE
GRPC support?

### ISSUE THREAD

**Issue by zj8487** [micro/go-micro#89]
Is there any plan to support the grpc transport?

**Comment by asim** [comment]
Are there ideas? Sure. Are there plans? Not yet. It's unclear what the best way is to support grpc. Whether as a transport, client/server or codec. 

How do you see it integrating?

**Comment by zj8487** [comment]
Thanks for your response and sorry for delay to response.
according to read the code, i think `transport, codec` is really hard to integrate.
i think a new `client/server`  is a better way.

but a more suggestion, If it has the same format to define the implementation for service is better.

**Comment by asim** [comment]
I agree. Its likely that it becomes a client/server integration. Having looked at https://github.com/grpc/grpc-go, I think we can reuse a lot of this but will have to rewrite quite a bit of the higher level interface to integrate with go-micro.

The other thing to note is that because of the tight coupling with HTTP2 it may not be possible to separate the transport. So a grpc client/server would ignore any transports provided.

**Comment by mrezai** [comment]
I briefly read this:  https://coreos.com/blog/gRPC-protobufs-swagger.html
and it seems related to this topic.
https://github.com/gengo/grpc-gateway used to build REST API on top of gRPC.

**Comment by asim** [comment]
Yuki Yugui is a great engineer. I need to read the code to see how the internals work and see if it helps with ideas on writing the client/server.
