### ISSUE TITLE
About gomicro performanc

### ISSUE THREAD

**Issue by pennkao** [micro/go-micro#997]
I run example github.com/micro/examples/service

call rpc in gin
func main() {
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {

		grt := greeter.NewGreeterService("greeter", nil)
		_, err := grt.Hello(context.TODO(), &greeter.Request{Name:"caonima"})
		if err != nil {
			//fmt.Println("err:", err)
		}

		//fmt.Println(req.Greeting, req.String())
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run(":9000") // listen and serve on 0.0.0.0:8080
}

2019/11/29 - 02:03:25 | 200 |  105.531414ms 
time  100ms

Remove rpc calls  time 307.097µs

Only rpc calls cost 100ms

**Comment by acynothia** [comment]
maybe the service discovery cost. u can try one more times.

**Comment by asim** [comment]
If you're using the default discovery system (mdns) then the first call can cost anywhere up to 100ms depending on what version you're running. This is because mdns doesn't just return all service entries, its a broadcast like system which requires you to wait a period of time and decide that you have enough values.

The second call will be faster because we cache the entries.

**Comment by pennkao** [comment]
I use etcd instead of the default discovery    cost  1ms  thinks

**Comment by vtolstov** [comment]
why you close the issue?
